---

# Add and remove as many hosts as you need based on the example below.

esxi_hosts:
  - hostname: host-01.local
    username: root
    password: password
  - hostname: host-02.local
    username: root
    password: password
