---

# Any backups older than this number of days will be removed.
# 0 = Disabled
backup_retention_days: 0

# Allows connection when SSL certificates are not valid.
# Set to 'false' when host certificates are not trusted.
validate_host_certs: true

# Destination directory for backup files.
# You must have a Docker volume bound to this path, e.g. `-v ./backups:/app/backups`.
backup_directory: /app/backups

# Add and remove as many hosts as you need based on the example below.
esxi_hosts:
  - hostname: host-01.local
    username: root
    password: password
  - hostname: host-02.local
    username: root
    password: password
