---

- name: ESXi Config Backup
  hosts: localhost
  gather_facts: false
  vars_files: [config.yml]
  tasks:
    - name: Backup ESXi config
      community.vmware.vmware_cfg_backup:
        hostname: "{{ item.hostname }}"
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        dest: "{{ backup_directory }}"
        validate_certs: "{{ validate_host_certs | default(true) | bool }}"
        state: saved
      loop: "{{ esxi_hosts }}"
      loop_control:
        label: "{{ item.hostname }}"
