---

- name: ESXi Config Backup
  hosts: localhost
  gather_facts: false
  vars_files: [config.yml]

  pre_tasks:
    - name: Gather datetime information
      ansible.builtin.setup:
        gather_subset: [date_time]

    - name: Construct filename
      ansible.builtin.set_fact:
        backup_filename: >-
          {{ [
              backup_directory,
              'configBundle-HOSTNAME-' + ansible_date_time['iso8601'] | replace(':','') | replace('-','') + '.tgz'
            ] | path_join 
          }}

  tasks:
    - name: Backup ESXi config
      community.vmware.vmware_cfg_backup:
        hostname: "{{ item.hostname }}"
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        dest: "{{ backup_filename | replace('HOSTNAME', item.hostname) }}"
        validate_certs: "{{ validate_host_certs | default(true) | bool }}"
        state: saved
      loop: "{{ esxi_hosts }}"
      loop_control:
        label: "{{ item.hostname }}"

  post_tasks:
    - name: Expired backup cleanup
      when: backup_retention_days | default(0) > 0
      block:
        - name: Find backups older than desired retention
          ansible.builtin.find:
            paths: "{{ backup_directory }}"
            patterns: [configBundle-*.tgz]
            file_type: file
            age: "{{ backup_retention_days }}d"
          register: old_backups

        - name: Remove backups older than desired retention
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ old_backups.files }}"
          loop_control:
            label: "{{ item.path }}"
